### ISSUE TITLE
Multicolumn Office 2016 Mac

### ISSUE THREAD

**Issue by chanioman** [krlmlr/Excel2LaTeX#18]
When trying to convert a table, frequently enough I get multicolumns. I understand that this is mainly due to large number of characters, but could there be an option whether we want the multicolumn-multirow on or off?
![screen shot 2017-03-23 at 16 58 40](https://cloud.githubusercontent.com/assets/11799515/24257283/bb974624-0fea-11e7-98c5-ce8ec7d8b362.png)

**Comment by chelh** [comment]
The `\multicolumn`s are probably happening because your alignment is set to **General** and there's text in the bottom row of the table. When Excel2LaTeX sees that, it aligns the whole column to the left by default. Then whenever it encounters something that's right-aligned (i.e., a number) it wraps the cell in a `\multicolumn` to change the alignment of that cell only.

You can fix this by setting the entire column to be right-aligned.

**Comment by chanioman** [comment]
Indeed you are right. Now it works amazingly well! I changed the alignment and now everything is fine. I am not sure however this issue should stay as an issue or not. After all, -and correct me if I am wrong- alignment is not what multicolumn is intended for.

**Comment by chelh** [comment]
If I do a quick search online, `\multicolumn` is indeed given as [the best way to change a single cell's alignment](http://tex.stackexchange.com/questions/47675/change-align-of-a-single-cell-in-tabular). There's a way to do it using `\hfill\vadjust{}`, but that's even more of a hack. So this is the least worst solution.
